_wandb:
    value:
        cli_version: 0.22.0
        e:
            d550jiy11v1hemfkcb8gv72f1dbccdh2:
                codePath: GRPO-Qwen-1.5-Instruct-Multi-GPU.py
                codePathLocal: GRPO-Qwen-1.5-Instruct-Multi-GPU.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "32212254720"
                        used: "17256443904"
                email: shumengyang246@gmail.com
                executable: /root/miniconda3/bin/python
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-5a9b4223-4a58-5b32-be66-f59821444cd9
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-d33e34ca-f608-4701-e0b8-5bf0b1671592
                host: autodl-container-69e24a8e18-05e17fcf
                memory:
                    total: "1081820241920"
                os: Linux-5.15.0-97-generic-x86_64-with-glibc2.35
                program: /root/GRPO/GRPO-Qwen-1.5-Instruct-Multi-GPU.py
                python: CPython 3.12.3
                root: /root/GRPO
                startedAt: "2025-09-30T02:27:23.461126Z"
                writerId: d550jiy11v1hemfkcb8gv72f1dbccdh2
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 2
                - 1
                - 3
                - 11
                - 41
                - 49
                - 51
                - 71
            "2":
                - 2
                - 1
                - 3
                - 11
                - 41
                - 49
                - 51
                - 71
            "3":
                - 2
            "4": 3.12.3
            "5": 0.22.0
            "6": 4.56.2
            "10":
                - 20
            "12": 0.22.0
            "13": linux-x86_64
